name: Link Checker

on:
  push:
    branches:
      - main
  schedule:
    # Run once a week on Monday at midnight
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Lychee Link Checker
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          args: --verbose --no-progress README.md
          fail: true # Fail the build if any broken links are found
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
